apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-image-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Image Tag
    policies.kyverno.io/category: Best Practices
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-fixed-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using image tag latest is not allowed in controlled deployments."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
