apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels
  annotations:
    policies.kyverno.io/title: Require Standard Labels
    policies.kyverno.io/category: Best Practices
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-app-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
                - Service
      validate:
        message: "Required labels app.kubernetes.io/name and app.kubernetes.io/component are missing."
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: "?*"
              app.kubernetes.io/component: "?*"
