apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api-config
  namespace: hsbc-demo
  labels:
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/component: api
data:
  APP_ENV: "kind"
  APP_RELEASE: "v1"
  DB_HOST: "postgres.hsbc-demo.svc.cluster.local"
