apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secret
  namespace: hsbc-demo
  labels:
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DB_USERNAME: "payment_user"
  DB_PASSWORD: "change-me-only-for-local-kind"
