apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: hsbc-demo
  labels:
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/component: api
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
